### ISSUE TITLE
About the motor rotation Angle 关于电机转动角度的问题

### ISSUE THREAD

**Issue by lvcc99** [bonezegei/Bonezegei_ULN2003_Stepper#1]
Hello, how can I use this library to rotate the motor to the Angle I want? Like 90 degrees。

**Comment by bonezegei** [comment]
Good Day,

I just added a function for step using Angle. The Direction  either 1 or 0 for FORWARD or BACKWARD. And Angle how many angles from the initial point the motor will rotate. 

stepAngle(Direction, Angle)

This new update has not been tested yet. Im on travel right now I can't test the library . But based on the datasheet for 28BYJ-48 – 5V Stepper Motor. The new function should work.  Thank you for suggesting this function.
